build: Upgrade spotless version to 2.43.0 (#85)
Current spotless `2.29.0` doesn't work with Apache Maven 3.9.6 + Java version: 21.0.2.
    
```
java.lang.reflect.InvocationTargetException
   at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:118)
  at java.lang.reflect.Method.invoke (Method.java:580)
...
Caused by: java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree com.sun.tools.javac.tree.JCTree$JCImport.getQualifiedIdentifier()'
...
```